### ISSUE TITLE
problem with BPMdetect.cpp counter

### ISSUE THREAD

**Issue by davephillips** [martin-lueders/ML_modules#13]
Hi Martin,

Linux Fedora 23 GCC 5.3.1

Building ML_modules for the latest dev Rack I've hit this snag:

g++ -D v_dev -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/BPMdetect.cpp.o src/BPMdetect.cpp
src/BPMdetect.cpp: In member function ‘virtual void BPMdetect::reset()’:
src/BPMdetect.cpp:45:25: error: ‘counter’ was not declared in this scope
  void reset() override {counter=0; onSampleRateChange();};
                         ^
../../compile.mk:53: recipe for target 'build/src/BPMdetect.cpp.o' failed
make: *** [build/src/BPMdetect.cpp.o] Error 1

I don't know how to fix this one. Any suggestions ?

**Comment by martin-lueders** [comment]
Sorry. This module is not finished yet. It is currently still for the version 0.4.0 rack sources, and none of my modules is yet ported to the development branch.

As people are still mostly using the 0.4.0 version, I decided to stick with that one for now, and convert once we are closer to the release of 0.5.0.

It has become impracticable to support both at the same time, although I will start porting them once the BMP counter and Voltmeter are finalized.

**Comment by davephillips** [comment]
Hey Martin, I understand, no problem, thank you for your reply. Fortunately, I know how to use 'git log' and 'git reset'. :)
