### ISSUE TITLE
modules missing NUM_LIGHTS

### ISSUE THREAD

**Issue by davephillips** [martin-lueders/ML_modules#15]
[dlphilp@The6300 src]$ grep NUM_LIGHTS *.*
FreeVerb.cpp:		NUM_LIGHTS
OctaFlop.cpp:		NUM_LIGHTS
Quantum.cpp:		NUM_LIGHTS
SeqSwitch2.cpp:                NUM_LIGHTS
SeqSwitch.cpp:		NUM_LIGHTS
ShiftRegister.cpp:                NUM_LIGHTS
TrigBuf.cpp:		NUM_LIGHTS

All these files include an incomplete module statement. For example, this :

FreeVerb() : Module( NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS ) {

will crash the latest Rack. This will fix the problem :

FreeVerb() : Module( NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, NUM_LIGHTS ) {

Best regards,

dp

**Comment by martin-lueders** [comment]
I have added all NUM_LIGHTS now. It builds on my system, so I hope it is fixed now.
