### ISSUE TITLE
build failure, latest dev Rack, latest git

### ISSUE THREAD

**Issue by davephillips** [martin-lueders/ML_modules#16]
Linux Fedora 23
dev Rack (latest pull), ML_modules (latest pull)

[dlphilp@The6300 ML_modules]$ make
g++ -D v_dev -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Quant.cpp.o src/Quant.cpp
In file included from src/Quant.cpp:1:0:
src/ML_modules.hpp:19:40: error: expected class-name before ‘{’ token
 struct RedMLKnob : RoundKnob, SnapKnob {
                                        ^
../../compile.mk:53: recipe for target 'build/src/Quant.cpp.o' failed
make: *** [build/src/Quant.cpp.o] Error 1

I'm lost at this point.

Best,

dp

**Comment by martin-lueders** [comment]
It seems that SnapKnob is no longer available in 0.5.0. I now removed that parent class. The knob behaviour will be continuous again. Values are still integer, though, so it does not matter.

**Comment by davephillips** [comment]
Thank you, Martin, and as always, thank you for the terrific modules. :)
