### ISSUE TITLE
Fails to build in Mint64

### ISSUE THREAD

**Issue by asbaklm** [martin-lueders/ML_modules#20]
src/OctaFlop.cpp: In constructor ‘OctaFlopWidget::OctaFlopWidget()’:
src/OctaFlop.cpp:138:26: error: ‘createValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(row2, offset_y + 8 +   i*delta_y), &module->out[i]));
                          ^
src/OctaFlop.cpp:138:54: error: ‘GreenValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(row2, offset_y + 8 +   i*delta_y), &module->out[i]));
                                                      ^
src/OctaFlop.cpp:138:54: error: template argument 1 is invalid
../../compile.mk:53: recipe for target 'build/src/OctaFlop.cpp.o' failed
make: *** [build/src/OctaFlop.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
src/ShiftRegister.cpp:82:7: error: virtual function ‘virtual void ShiftRegister::initialize()’
  void initialize() override {
       ^
In file included from ../../include/rack.hpp:7:0,
                 from src/ML_modules.hpp:1,
                 from src/ShiftRegister.cpp:1:
../../include/engine.hpp:72:15: error: overriding final function ‘virtual void rack::Module::initialize()’
  virtual void initialize() final {}
               ^
src/ShiftRegister.cpp: In constructor ‘ShiftRegisterWidget::ShiftRegisterWidget()’:
src/ShiftRegister.cpp:144:12: error: ‘createValueLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(offset_x, offset_y + 8 +   i*delta_y), &module->values[i]));
            ^
src/ShiftRegister.cpp:144:40: error: ‘GreenValueLight’ was not declared in this scope
   addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(offset_x, offset_y + 8 +   i*delta_y), &module->values[i]));
                                        ^
src/ShiftRegister.cpp:144:40: error: template argument 1 is invalid
../../compile.mk:53: recipe for target 'build/src/ShiftRegister.cpp.o' failed
make: *** [build/src/ShiftRegister.cpp.o] Error 1
src/VoltMeter.cpp:65:8: warning: ‘virtual void VoltDisplayWidget::draw(NVGcontext*)’ can be marked override [-Wsuggest-override]
   void draw(NVGcontext *vg) {

**Comment by martin-lueders** [comment]
what version are you building against? Make sure you edit the Makefile correspondingly. You might need to change the -D v040 to -D v_dev

**Comment by asbaklm** [comment]
I see, much obliged I will check the Makefile and adjust. Thanks again for these awesome modules and the even more awesome PG-8X
