### ISSUE TITLE
request disguised as a suggestion

### ISSUE THREAD

**Issue by joopvdl** [martin-lueders/ML_modules#22]
Hey Martin, I don't know if this is the right place, but I wouldn't bother you about it in the facebook group, but I have a suggestion (and, of course, it is basically a request)
I use sequential switch a lot. Very useful. But, 8 out of 10 times, I just use two positions. So it functions as a trigger activated on/off switch.
Could you make a version of sequential switch that has just 2 positions? Maybe even make it have 4 of those, so there's 4 trigger activated on/off switches. All of them with both options, up and step.
I have not found switches in any plugin collection that do this, just the switch from mental but that's only functioning in your "step" mode. But I prefer the other one.
I apologise in advance if this is inappropriate, or in the wrong place, but I would really find this very useful.

thank you, Joop

**Comment by martin-lueders** [comment]
Hi Joop,

I am not sure I understand your suggestion. What would be different than the current one when you set the red knob to 2? That restricts the number of steps you can cycle through, and it will behave exactly the way I understand what you want.

**Comment by joopvdl** [comment]
Yes, that's how I use it now. But it feels a bit as if I waste a fine instrument by using only part of it. Like owning a Ferrari and not using 5th gear, or so. And also it would save some screen space, if  some  of these switches are combined into one module. But, as it is now, it works perfectly fine, so maybe I shouldn't have asked. 
Thank you for your great modules, using them all the time. 
Joop

**Comment by martin-lueders** [comment]
Well, apart from screen estate, you are not wasting anything. The CPU cycles for a 2-state version would be the same as for the 8-state version, limited to two.

Currently, my philosophy is to offer more, and let the user restrict it. That will also be true for the two complex (and probably commercial) sequencers I am working on at the moment.

Which switch are you mainly using? 8->1 or 1->8. Maybe, if I have some spare time one day, I can swite a cut-down version. Would it make sense to combine both into one module?

**Comment by joopvdl** [comment]
I am using 8-1 more than the 1-8. I am using both, though. 
But the two-way switch would have a different function.
8-1 can be used to select between patterns, sections, scales, notes, etc.
2-1 would be more to introduce a new element to the patch, or a modulation, or an entirely different section.
I try to keep my patches organised, by keeping the elements on their own row. With a logical flow from left to right.
That means a combination of the two would have me using just one of them, in the section where it is needed. (That's an advantage of a digital rack, it's easier to keep some sort of organisation.)
So a narrow (3px) module that would contain 4 of these switches (or less, if it wouldn't fit) would be what I had in mind.
Oh, and please consider the first package of your sequencers sold :)

**Comment by joopvdl** [comment]
I just realised there should also be a reset input, so it might get a bit crowded in 3px :)
And one more suggestion (..): I love your counter. And it's usually connected to a switch (see above). You might consider a combination of the two.

**Comment by martin-lueders** [comment]
OK. an 8-fold binary switch is on the way. Each line has 3 inputs and one output. The first input is the switch voltage, then CV A and CV B. If the switch voltage is above a certain threshold, the output is B otherwise A.

The threshold can be adjusted by knob or CV value.

**Comment by joopvdl** [comment]
That's just wonderful.

**Comment by martin-lueders** [comment]
I hope these new modules fit your requirement.

**Comment by joopvdl** [comment]
Yes, they do!
Thank you so much.
And if you, in the future, need any help, I'll be glad to provide that.

Joop


2018-01-08 10:10 GMT+01:00 martin-lueders <notifications@github.com>:
