### ISSUE TITLE
OctaFlopWidget Errors.

### ISSUE THREAD

**Issue by Cordoha** [martin-lueders/ML_modules#24]
Just some errors I'm getting when compiling in 0.5.0. 

src/OctaFlop.cpp: In constructor ‘OctaFlopWidget::OctaFlopWidget()’:
src/OctaFlop.cpp:138:26: error: ‘createValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(r
                          ^
src/OctaFlop.cpp:138:54: error: ‘GreenValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(r
                                                      ^
src/OctaFlop.cpp:138:54: error: template argument 1 is invalid
../../compile.mk:53: recipe for target 'build/src/OctaFlop.cpp.o' failed

src/OctaFlop.cpp: In constructor ‘OctaFlopWidget::OctaFlopWidget()’:
src/OctaFlop.cpp:138:26: error: ‘createValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(r
                          ^
src/OctaFlop.cpp:138:54: error: ‘GreenValueLight’ was not declared in this scope
                 addChild(createValueLight<SmallLight<GreenValueLight>>(Vec(r
                                                      ^
src/OctaFlop.cpp:138:54: error: template argument 1 is invalid

**Comment by tildebyte** [comment]
Yes, this. Fedora 26, current master. Rack itself builds and runs, as do the "stock" plugins. Some 3rd-party plugins (e.g. bid00) work as well.

**Comment by martin-lueders** [comment]
I just saw that the Makefile still contained -D v040. I changed that now to -D v_dev.
Should build correctly now.
