### ISSUE TITLE
Linux Release

### ISSUE THREAD

**Issue by t0m5k1** [martin-lueders/ML_modules#26]
Please can we have a Linux release?

**Comment by phdsg** [comment]
[ML_modules-devfe0a46d-lin.zip](https://github.com/martin-lueders/ML_modules/files/1503882/ML_modules-devfe0a46d-lin.zip)

**Comment by t0m5k1** [comment]
Thank you so much :)

**Comment by martin-lueders** [comment]
As Linux releases are now routinely included, I close this issue.
