### ISSUE TITLE
Request for permission to redistribute Quantum Mod under GPL

### ISSUE THREAD

**Issue by Aepelzen** [martin-lueders/ML_modules#27]
Hi, I'm not sure if this is the right way to do this since this isn't really an issue but i couldn't find a way to contact you directly.

I made a 4 channel version of Quantum and would like to include that in my own module pack (that you allready seem to have discovered ^^). However, my modules are released under the GPL3.0 which seems to collide with your license (specifically the part about including your license). Is it okay if i do so?

I would credit you in the module description and make it clear that all the real work was done by you.

Thanks

**Comment by martin-lueders** [comment]
Hi,

thanks for your interest. To be honest, I am not sure how to handle that. I am planning to release some commercial modules, which might re-use code of my free modules. This would not be possible, of I released my free modules under GPL. For that reason, I am not a big fan of GPL. I had a short discussion with Andrew Belt about this, and he also recommended to stay away from GPL (hence the lack of some of the Mutable modules).

As for the Quantum, I was planning to write a Mk II anyway in the next weeks (possibly commercial), including a memory for scales which can be stored and recalled through CV, as well as more channels. This would probably cover what you were planning to do. I might throw a 4 channel version (without storage) into the free pack, though.

**Comment by Aepelzen** [comment]
Thanks for the info. I am not an expert on licensing issues but me releasing my modification under the GPL would not change anything for your original version, would it?

As i understand it, the copyleft part of the GPL would only come into play if you were to reuse my version.

Anyway, thanks for taking your time to consider this and your work in general.

**Comment by Aepelzen** [comment]
Nevermind, i made my own.
