### ISSUE TITLE
New Modules

### ISSUE THREAD

**Issue by blackearth2014** [martin-lueders/ML_modules#30]
Great work Mr. Martin-Lueders on the new modules.

**Comment by martin-lueders** [comment]
Thanks! Hope they are useful and you enjoy them

**Comment by blackearth2014** [comment]
I have notice that you only have  a sum module with 8 in and 1 out. Do you have plans to develop a 1 in and 8 out multiple?

**Comment by blackearth2014** [comment]
I not include the Trigger Switch which operates on another level.

**Comment by martin-lueders** [comment]
A 1 to 8 multiple is not necessary, as you can stack cables. If you still need one, Autodafe has one.

**Comment by blackearth2014** [comment]
Thanks
