### ISSUE TITLE
0.5.3 branch refs TrigSwitch2 but src/TrigSwitch2.cpp is missing from branch

### ISSUE THREAD

**Issue by alikins** [martin-lueders/ML_modules#32]
After building the 0.5.3 branch, get warning on startup about the missing TrigSwitch2 symbol

[warning] Failed to load library ./plugins/ML_modules/plugin.so: ./plugins/ML_modules/plugin.so: undefined symbol: _ZN17TrigSwitch2WidgetC1Ev

src/ML_modules.cpp references it, but looks like src/TrigSwitch2.cpp didn't get added to git

(was testing 0.5.3 branch to see if I should add it to https://github.com/alikins/Rack-plugin-submodules v0.5 branch)

**Comment by martin-lueders** [comment]
Should be fixed in the new release
