### ISSUE TITLE
ML Modules v0.5.3: near unreadable displays

### ISSUE THREAD

**Issue by DomiKamu** [martin-lueders/ML_modules#33]
Hi,

For following modules, red digits are too difficult to read on grey background.
Concerns: Octaswitch, Evolution, Counter, BPM Tool, and Volt Meter.

Regards.

**Comment by martin-lueders** [comment]
Thanks, I am considering a high contrast option for future releases.

**Comment by DomiKamu** [comment]
IMO simply by changing "VCV Rack grey" default background (for digits) by pure Black, will be enough. Otherwise your modules are perfect, thanks a lot for them!

**Comment by martin-lueders** [comment]
Increased the contrast. Let me know how that is for you.

**Comment by DomiKamu** [comment]
Thanks Martin, now it's largely better! Thank your very much, you can close this ticket, of course.
