### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by ATGC2** [martin-lueders/ML_modules#39]
Dear Herr Martin Lueders,

i'm a Newbe in Programming, so i need some Help please.
My Question is the following:
Even when i try to build your Plugin File for OSx, i get the following Messages:

Last login: Thu Mar 22 08:14:19 on ttys000
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile ; exit;
MacBook-Air:~ VincenzoLuciano$ /Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile ; exit;
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 1: SLUG: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 2: VERSION: command not found
: command not foundano/Rack/plugins/ML_modules-master/Makefile: line 3: 
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 4: FLAGS: command not found
: command not foundano/Rack/plugins/ML_modules-master/Makefile: line 5: 
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 6: wildcard: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 6: SOURCES: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 7: wildcard: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 7: SOURCES: command not found
: command not foundano/Rack/plugins/ML_modules-master/Makefile: line 8: 
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 9: wildcard: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 9: DISTRIBUTABLES: command not found
: command not foundano/Rack/plugins/ML_modules-master/Makefile: line 10: 
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 11: RACK_DIR: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 12: RACK_DIR: command not found
/Users/VincenzoLuciano/Rack/plugins/ML_modules-master/Makefile: line 12: include: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Prozess beendet]

Danke im Voraus - Thanks in Advance

**Comment by ATGC2** [comment]
Please explain me what i do wrong.

**Comment by martin-lueders** [comment]
Can you please let me know which version of Rack you are using, and which branch of my plugins?

**Comment by ATGC2** [comment]
OK Mr Lueders,
the issue above was a mistake of mine.
I should describe exactly what i think, that it could be wrong.

1. i have installed as usual the VCV Rack in the Programm Folder of my MacBook and it works fine.
2. the Plugins Folder is in the Document Directory and it works fine also.
3.  i alway copy the various Plugins-Dylibs and all works fine.
4. i build the Rack to building the Plugin, in the user Directory and now the building of the Plugins woks fine, like described in the various Tutorials, but when i copy the builded Dylib of the Plugin in the Plugin Folder, the installed VCV Rack don't list it, in the drop down menu to choise it.

**Comment by martin-lueders** [comment]
My suspicion is that your Rack installation does and my plugins are not of the same version.

Could you, please, in your Rack directory do a 'git status' and also do the same in the plugins/ML_module directory.

Make sure both are either 0.6 or both 0.5.x

If they don't match, it won't work.

**Comment by ATGC2** [comment]
Right, it is the Point.
Your "ML Module" are V. 0.6 and the installed Rack on my Mac is V. 0.5.1.

i've tryed  to do a 'git status',  but i'm to new in this, so that it take a lot of time for now.

**Comment by martin-lueders** [comment]
In the ML_modules directory, please try the following commands:

git checkout v0.5
git pull

make clean
make

This should do the trick.

Did you try to download the binaries (see releases on my github page)?

There is not much sense in compiling for 0.5 now, as Rack 0.6 will come out in a few days.

**Comment by ATGC2** [comment]
Jes Mr Lueders, allready done with the Binaries and it works fine, but i try to learn, how to build it on myself.

Waiting for the new Rack 0.6, makes sense.
I thank You for your Patience.

**Comment by martin-lueders** [comment]
You can already play withRack 0.6 if you checkout 'master' in the Rack repository and build that version of Rack. As I can see it, Andrew is very close to releasing, as he is already testing the VST Bridge.

As you can see from my repository, my plugin is ready for 0.6. I just want to address some of the other issues first before finally releasing it.

**Comment by ATGC2** [comment]
Good to knows,

by the way, i appreciate your Work very much, in all aspect and use them all the time.
