### ISSUE TITLE
Rack crashes when connecting Seq Switch 1->8 to Triggered Switch 1->8

### ISSUE THREAD

**Issue by jacoblast** [martin-lueders/ML_modules#42]
Rack 0.6.0 on Ubuntu Linux says:

Rack: src/engine.cpp:221: void rack::engineAddWire(rack::Wire*): Assertion `!(wire2->inputModule == wire->inputModule && wire2->inputId == wire->inputId)' failed.

This happens when I connect the 8 outputs of seq switch to the 8 trigger inputs of trig switch, then connect anything to an input of the trig switch.
![ml modules crash](https://user-images.githubusercontent.com/37922721/41203697-a8c6a4f6-6c8f-11e8-9e60-2ce44f9790aa.png)

**Comment by martin-lueders** [comment]
Thanks for letting me know. I know that there was a bug in the old version. Can you, please, try to update to the new version (with the new GUI) and check whether it still crashes?

**Comment by jacoblast** [comment]
Oh yes I didn't notice, mine wasn't updating to 0.6.2 automatically. Thanks!

**Comment by martin-lueders** [comment]
Can you confirm that this is working for you now?

**Comment by jacoblast** [comment]
Yes, working fine.

**Comment by martin-lueders** [comment]
Thanks for confirming.
