### ISSUE TITLE
Sugestion: Quantum - Key Linking

### ISSUE THREAD

**Issue by cshaw340** [martin-lueders/ML_modules#43]
I use Quantum all of the time. If I had one request it would be a way to connect multiple modules together so that note selections on one module would be reflected in the others. Perhaps a "Key Link in" and "Key link Out" jack? 
I was originally going to request a new module that had multiple ins and outs but the ability to link multiple modules would seem a bit easier to implement.

Just a thought.
Love the work you are doing!

**Comment by martin-lueders** [comment]
That is essentially what the "Quantum Multiverse" is doing. It combines 8 instances of Quantum with one common note selection, plus some other features, such as a scale memory.

**Comment by cshaw340** [comment]
Ugh! I feel very foolish now. 
Thanks for your patience!
