### ISSUE TITLE
Volt Meter precision increase

### ISSUE THREAD

**Issue by veryfungi** [martin-lueders/ML_modules#45]
Hello Mr. Lueders
I'm a big fan of your modules! Thank you so much for making them available. I would like to bring to your attention an improvement that would make your Volt Meter even more awesome. Would it be possible to increase the display to 3 decimal places? Another idea would if you could move the existing displays and plugs up a bit you could add Min, Max, and Reset buttons at the bottom that would effect only the bottom display. Connect it to a voltage source and press reset. The display shows the highest voltage read in real time. Press Min the display shows the lowest voltage measured in real time. Press Max to again display the highest voltage measured. Press reset any time needed. Thanks again!

**Comment by martin-lueders** [comment]
Hi, 

Thanks for the suggestions. I will think about it when I update my modules to v 1.0.

Thanks

**Comment by veryfungi** [comment]
I noticed the improvement is implemented, very nice! thanks!
