### ISSUE TITLE
Segmentation Fault in Debian

### ISSUE THREAD

**Issue by tank-trax** [martin-lueders/ML_modules#46]
I am able to build v1 modules and they appear in the list of modules and load. Occasionally when selecting modules and filtering ML_modules VCV Rack will seg fault and crash

**Comment by martin-lueders** [comment]
Thanks. Next week I should have access to a Debian machine again, and will test it.
Which Debian are you running?

**Comment by tank-trax** [comment]
I am running Debian Stretch 9.9.

**Comment by tank-trax** [comment]
this does not appear to be happening any longer with the recent builds of Rackv1
will re-open if need be
thanks
