### ISSUE TITLE
Rack v1: Invalid tag in plugin.json

### ISSUE THREAD

**Issue by cschol** [martin-lueders/ML_modules#48]
The manifest validator script found the following issue in your `plugin.json`:

```
Validating ML_modules
Evolution: invalid tags: Serquencer
authorUrl: no URL specified
```

`authorUrl` is optional, but the invalid tag needs to be fixed.

**Comment by martin-lueders** [comment]
fixed. new commit is 7e7cae1df85853dc37c11af3f405b6f977cb79cc

**Comment by martin-lueders** [comment]
Solved.
