### ISSUE TITLE
small issue about paths

### ISSUE THREAD

**Issue by antoniograzioli** [martin-lueders/ML_modules#5]
I had blank panels after building your modules, simply because your repo is "ML-modules" but the code uses "plugins/ML_modules" for graphics

just renaming it corrrected the issue

**Comment by martin-lueders** [comment]
I noticed that.

I am not quite sure how to solve it.  I don't seem able to rename the repository. And I am a bit fearful that having a '-' in the path might give problems on some platforms.

I guess (hope!) that with the 0.4.0 version and the asset() function, the pathname should no longer be relevant.

**Comment by antoniograzioli** [comment]
yes, v 0.4.0 should solve the problem, since you simply write:

`panel->setBackground(SVG::load(assetPlugin(plugin,` "res/MyImage.svg")));

so the folder shouldn't be relevant anymore.

BTW you can rename your repo by simply going to "Settings" on top of your repo (that's what I did this morning ) ^^

**Comment by martin-lueders** [comment]
I renamed the repository now. If you already have it cloned, simply rename the ML-modules directory to ML_modules.

Anyway, with rack 0.4.0 that should become irrelevant.
