### ISSUE TITLE
Sum8 v1 distorts

### ISSUE THREAD

**Issue by espenstoro** [martin-lueders/ML_modules#51]
Hi.
Just trying out the v1 build posted here. I notice that Sum crackles and distorts with any number of inputs connected. Rack 1.0.0, Windows 8.1.

**Comment by martin-lueders** [comment]
Thanks! This is a stupid bug I introduced just before committing to the library. Will be fixed in next release.

**Comment by martin-lueders** [comment]
That should work now. Please, reopen the issue if you still have problems.
