### ISSUE TITLE
Quantum Note Toggle not working in 1.0

### ISSUE THREAD

**Issue by MaZe6K** [martin-lueders/ML_modules#53]
Hello!

First of all Thank You for your great modules!

It appears that the Note Toggle of Quantum is not working in 1.0. My uninformed non-coder guess is that this has something to do with polyphony. It reacts to a polyphonic signal, but the notes switch off after the gate ends. With a monophonic signal all notes stay off all the time.

**Comment by martin-lueders** [comment]
Sorry, I did not manage to write a new manual yet. This is not a bug but a
feature.

If the note select and note toggle are monophonic, it reacts as before.
When these cables are polyphonic, it toggles each note with the
corresponding gate, i.e. you can play the Quantum like an arpeggiator with
a keyboard.

I might implement a menu settings to prevent that and force the old way,
even with polyphonic inputs.

**Comment by MaZe6K** [comment]
Oh that's actually really nice! So with polyphonic input it's working and I love it!

But with monophonic input it doesn't work for me at all - all lights stay off when note and toggle are connected to a monophonic signal here (on Windows 7).

**Comment by martin-lueders** [comment]
Should be fixed in the next version. I also noticed some issues with that
and I am working on it.

**Comment by MaZe6K** [comment]
Everything working beautiful now! Thank You!
