### ISSUE TITLE
QUANTUM DCD OFFSET

### ISSUE THREAD

**Issue by Jairodallos** [martin-lueders/ML_modules#55]
Hello Martin
nice to greetings you.

You can see an issue discovered in your quantum module in comparison with others.

Thanks
![DC OFFSET](https://user-images.githubusercontent.com/22566357/60384323-d0e91a00-9a41-11e9-8903-e87dc0fe339e.png)

**Comment by martin-lueders** [comment]
Hi,

I don't understand you patch. You are sending a audio signal through the
Quantum, and also you have not selected any notes.
In this case, the output of Quantum is basically undefined and will be a
constant, which you seem to be adding to the original output of the VCO.

A Quantizer should be used in the signal path of the pitch CV which goes
into the V/Oct input of the oscillator, not into the the audio signal path
after the VCO.

You can see a nice tutorial on the Quantum by Omri Cohen on Youtube:
https://www.youtube.com/watch?v=1rz8u0b30mM

Hope it helps,
Martin

**Comment by Jairodallos** [comment]
Hello Martin
yes, this patch in the sented image is no using any quantized note in order to show you the DC offset

Please open the patch sented this time and you can "see and Listen" the change disconnecting/connecting the cable from QUANTUM to PATCH (or any of the inputs in patch)

Is generating an audio issue
Regards

if you create t
[QUANTUM DC OFFSET.zip](https://github.com/martin-lueders/ML_modules/files/3343957/QUANTUM.DC.OFFSET.zip)

**Comment by martin-lueders** [comment]
Hi Jairo,

You are using the module in the wrong way. Please, refer to the
documentation and the video, I linked.
The Quantiser is NOT supposed to be in the Audio path, but in the CV pitch
signal path. Also, you need to select some notes to be allowed in the scale.

The way you have connected the module, it is clear that it produces just a
constant, which then is added to the audio signal, producing the DC offset.

the signal path should be:

(LFO or sequencer or Sample&Hold) -> Quantum IN, Quantum OUT -> VCO V/Oct
in, VCO out -> (mixer, filter, vca, etc.)

Best Regards,
Martin

**Comment by Jairodallos** [comment]
Hello Martin
yes, the error was mix the signals
Thanks for your aclaration

In this software all is possible
:)
