### ISSUE TITLE
Trigger Switch 1:8 - Signals 3 through 8 get 'Stuck' When Not Selected

### ISSUE THREAD

**Issue by gristleism** [martin-lueders/ML_modules#56]
![gif of issue](https://i.imgur.com/iuiuewd.gif)

In rack version 1.1.1 using updated modules from plugin manager. The operating system is OS X Mojave 10.14.5 

To recreate the issue: 
- Feed a constant voltage into the 'in' port. 
- Send any of outputs 3 through 8 to a Scope. 
- Manually trigger any of outputs 3 through 8, and it will start sending the signal. 
- Manually trigger Output 1 - the signal being output by three through 8 will continue sending even though it is not selected. 

p.s. Thank you for all of your work! I use these modules on a more-or-less daily basis.

**Comment by martin-lueders** [comment]
Thanks for reporting. I will look into it.

**Comment by martin-lueders** [comment]
I can confirm the behavior and it will be fixed in the next update.

**Comment by martin-lueders** [comment]
This should be fixed now.
