### ISSUE TITLE
Triggered Switch 1x3 to 8x3 V1.0.2

### ISSUE THREAD

**Issue by ContemporaryInsanity** [martin-lueders/ML_modules#58]
Only the top row of outputs work.
Linux Mint 19.1.

**Comment by smerkley** [comment]
I'm having the same issue, and the top row doesn't work polyphonically either, I'm on Win7.

**Comment by ContemporaryInsanity** [comment]
Will this ever be fixed or is this abandonware now?

**Comment by martin-lueders** [comment]
Sorry for the silence. My life has been (and still is a bit) upside down
the last couple of month. Moved country, started new job, sold house,
having to fix the new flat, etc. I really did not find any time for Rack
development.

Now things are slowly getting back to normal and I am actually working on
it right now. Just need to do some more detailed checks. and will hopefully
release the fixed version soon. Definitely no abandonware.

Cheers,
Martin

**Comment by ContemporaryInsanity** [comment]
Aaah, right, good to hear.  All the best with what sounds like a complete change of life!
