### ISSUE TITLE
Directory name conflict...

### ISSUE THREAD

**Issue by tildebyte** [martin-lueders/ML_modules#6]
...between dist dir in Makefile introduced @ 1f2beca8 ("ML_Modules") and paths in plugin source files ("ML_modules") @ HEAD, e.g. [Quant](https://github.com/martin-lueders/ML_modules/blob/a637eb9d0a7ecc24814f23f06ac0feed4999c82c/src/Quant.cpp#L68). I'd submit a PR, but I don't know how you want to resolve it.

**Comment by martin-lueders** [comment]
I just updated the Makefile. Should now be all consistent with ML_modules.
Just rename your directory. In case things get messed up, just delete all and clone it again.

**Comment by tildebyte** [comment]
Thanks!
