### ISSUE TITLE
Sequential Switch -Suggestion Re Randomisation

### ISSUE THREAD

**Issue by 77377** [martin-lueders/ML_modules#60]
Hi Martin, sorry to bother with a kind of a silly request. I'm aware that the very name of sequential switch implies the opposite of what I'm asking.....but 

Would it be possible to add perhaps a right hand menu option of switching randomly between inputs/outputs when receiving a trigger on the  up/down inputs? (:

Cheers!

**Comment by martin-lueders** [comment]
Hi. Sorry for the late reply.

I will see in the next update, whether I can accommodate another trigger
input for Random without screwing up the GUI too much. If not, which input
do you think one could sacrefize?

Cheers,
Martin

**Comment by martin-lueders** [comment]
This is added now since  version 1.0.4
