### ISSUE TITLE
OctaSwitch: Missing setChannels()

### ISSUE THREAD

**Issue by netboy3** [martin-lueders/ML_modules#61]
https://github.com/martin-lueders/ML_modules/blob/5faba73c9d7ff5301d84678a0d6b2db570edf79c/src/OctaSwitch.cpp#L65

You should setChannels(channels) on the output ports to enable polyphony on those ports. Currently the output ports are monophonic.

**Comment by martin-lueders** [comment]
Done. Thanks for pointing out.
