### ISSUE TITLE
Cloner is missing from plugin.json

### ISSUE THREAD

**Issue by Revheim** [martin-lueders/ML_modules#62]
Well, the whole issue is in the title.

**Comment by martin-lueders** [comment]
I also noticed. In the meantime I also started some improvements to cloner,
adn will officially add it in the next release.
In the meantime, just edit the plugin.json file and add:

    {
      "slug": "Cloner",
      "name": "Cloner",
      "description": "Clone a signal to polyphonic channels",
      "tags": ["Utility, Polyphonic"]
    }

**Comment by Revheim** [comment]
Brilliant, thanks :)
