### ISSUE TITLE
 Add URLs to individual module manuals

### ISSUE THREAD

**Issue by AndrewBelt** [martin-lueders/ML_modules#66]
VCV Rack and the VCV Library support per-module manual URLs. Simply add a "manualUrl" property to each module object in the plugin.json manifest. https://vcvrack.com/manual/Manifest#modules-manualurl If you change your wiki manual to use headers (e.g. `### FreeVerb`) instead of bullet points, you can link directly to that section on the page. Example:
```json
    {
      "slug": "FreeVerb",
      "name": "FreeVerb",
      "moduleUrl": "https://github.com/martin-lueders/ML_modules/wiki#freeverb",
      "description": "VCV Rack implementation of the good old Freeverb",
      "tags": ["Effect","Reverb"]
    },
```

**Comment by martin-lueders** [comment]
Thanks for the comment. This is done now since the last release.
