### ISSUE TITLE
trigswitch 8x3 and 8x3 polyphony

### ISSUE THREAD

**Issue by joopvdl** [martin-lueders/ML_modules#67]
Hey Martin, I am running into this problem:
When connecting a polyphonic signal to the 1x3 to 8x3 triggered switch, the outputs stay monophonic.

I think that would not be the intention, unless I am using it in another way than intended.

Best, Joop

**Comment by martin-lueders** [comment]
Indeed, this is a bug. I will have to see how to fix it.

In the meantime, I found a workaround: If you _first_ connect the Out and then the In, it recognizes the number of channels.

Cheers,
Martin

**Comment by joopvdl** [comment]
I also have the impression that it's ok after restarting Rack.

Joop

**Comment by martin-lueders** [comment]
This will be fixed in 1.1.3 which is submitted to the library.
