### ISSUE TITLE
"Arm on Load" option for Trigger Buffer

### ISSUE THREAD

**Issue by benirose** [martin-lueders/ML_modules#68]
Trigger Buffer is fantastic and allows me to do some more controlled randomization, but I always have to remember to arm them when I boot up a patch. Any possibility of an "Arm on Load" parameter we can check so it's armed next time the patch loads?

**Comment by martin-lueders** [comment]
Good Idea. I will consider it for the next release, if it is not too complicated.

**Comment by martin-lueders** [comment]
This feature will be available in the upcoming v2 release.
