### ISSUE TITLE
h-bar quantizer not working

### ISSUE THREAD

**Issue by davephillips** [martin-lueders/ML_modules#7]
Hi Martin,

I had no trouble building your modules for VCV Rack 0.4.0, but it seems the Quantizer isn't working, no signal is getting through. The Quantum and Sequential Switch modules work fine, I haven't tested the others yet. Thanks for updating your modules, they're great additions to the Rack.

Best,

dp

**Comment by martin-lueders** [comment]
On which system are you trying?

**Comment by martin-lueders** [comment]
Oops.

I just spotted the typo.  The compiler directives around the lines `out.value = result` are wrong. There is a `#ifdef v40` which should be replaced by `#ifdef v040`. Will correct that now...

**Comment by davephillips** [comment]
Thanks, that fixed the problem. The quantizer is now working perfectly with 0.4.0 (pre) and 0.3.2.

**Comment by martin-lueders** [comment]
OK. Good to know. Thanks for pointing out the error.
