### ISSUE TITLE
v2: missing knob SVG

### ISSUE THREAD

**Issue by cschol** [martin-lueders/ML_modules#71]
The following warning appears in the Rack log:

```
[1.019 warn src/window/Svg.cpp:112 load] Failed to load SVG /home/cschol/src/Rack-2.0-Home/plugins/ML_modules/res/NewRedKnob_28_bg.svg
```

Looks like `NewRedKnob_28_bg.svg` is missing from the repository.

**Comment by martin-lueders** [comment]
Thanks for pointing this out. The problems was simply a wrong filename in ML_components.cpp. However, the component was not used in the plugin.

But I fixed the problem in the latest commit. A rebuild of the module should not be necessary.

**Comment by cschol** [comment]
Sounds good. Thanks. It will just be included in the next update.
