### ISSUE TITLE
Wrong link in wiki

### ISSUE THREAD

**Issue by ThePython10110** [martin-lueders/ML_modules#72]
The Mixers link on the wiki's homepage is currently `https://github/martin-lueders/ML_modules/wiki/Mixers`, but it should be `https://github.COM/martin-lueders/ML_modules/wiki/Mixers` (forgot the `.com`)
Also, it hasn't been updated to Rack 2 (no Sum Mk III).

**Comment by martin-lueders** [comment]
Thanks for pointing out the wrong link. This is fixed now. The update to version 2 will follow soon, but not much has changed in the functionality. So, the old documentation will just be fine for now. Sum MK III is not yet finished. It ended up in the release accidentally, but the functionality should be straight forward. In comparison with Mk II, the 3-way slider now has the positions -1, 0, 1, or in words, negative polarity, mute, and positive polarity,
