### ISSUE TITLE
Quantum multiverse lack of version number

### ISSUE THREAD

**Issue by W4too** [martin-lueders/ML_modules#73]
Hi, 

It seems that, with the last version of VCV (2.1.2), Quantum multiverse asks for an update due to the lack of version number.
![quantum_version](https://user-images.githubusercontent.com/100092785/177828287-48aa2d3e-8c0e-4461-97ca-a7b782e6cb27.jpg)

Thanks

**Comment by pgatt** [comment]
2.1.1 also

**Comment by martin-lueders** [comment]
The fix for that is now submitted to the VCV team and should hopefully hit the library soon. Thanks for pointing out the problem.
