### ISSUE TITLE
Quantum crash on macOS Catalina

### ISSUE THREAD

**Issue by povesteam** [martin-lueders/ML_modules#74]
Hello

I like your quantizer, and it works fine most of the time.

But I got into an edge case and I cannot get it to work:
When I link Trigger in first Quantum to Toggle in second Quantum, VCV Rack crashes every time.

This is exactly what I try to do [at minute 8:33 in Omri Cohen's video Comparing Quantizers in VCV Rack](https://www.youtube.com/watch?v=TclzkP67tDs&t=513s).

I have attached the VCV Rack file saved just before the crash, and a screenshot with the cable I am dragging just before the crash.

I am using macOS Catalina 10.15.7, VCV Rack Free 2.1.2, Quantum 2.0.0.

If there is any information that would help you debug, I will gladly provide it.

Thank you for your great work!

[quantum-debug.vcv.zip](https://github.com/martin-lueders/ML_modules/files/9335269/quantum-debug.vcv.zip)

<img width="266" alt="Screenshot 2022-08-15 at 08 32 20" src="https://user-images.githubusercontent.com/506532/184581668-56a30368-d6bb-475d-ab07-60a7e66a78c2.png">

**Comment by martin-lueders** [comment]
Hi!
Sorry for the delay. It's a busy time at work right now. Thanks for reporting the bug. I managed to reproduce the crash in a further simplified setup. My suspicion is that things go wrong when you toggle notes and inbetween change the transpose input. I will have to investigate further...

Cheers,
Martin

**Comment by martin-lueders** [comment]
The bug fix has been submitted to the library (update to version 2.0.1) and should be in the library soon.

**Comment by povesteam** [comment]
I see it was a problem of transposing above 12 or below 0, I'm glad you caught it.
Thank you very much for the fix!
